name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TEST
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: TEST
        setup-command: ''
        command: javac CompositeNumbers.java && java CompositeNumbers
        input: '50'
        expected-output: 4 6 8 9 10 12 14 15 16 18 20 21 22 24 25 26 27 28 30 32 33
          34 35 36 38 39 40 42 44 45 46 48 49 50
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
